#!/bin/bash

## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## generic deb clean script version 0.1

set -x

set -o pipefail

fakeroot debian/rules clean
